name: GitHub Actions customs variables  demo
run-name:  GitHub Actions customs variables
on: [push]
env:
  API_KEY: "123456_set_at_workflow_level"
jobs:
  Run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository code
      uses: actions/checkout@v4
    - name: get python version
      run: python --version
    - name: Run script
      run: python test.py
