name: GitHub Actions customs variables  demo
run-name:  GitHub Actions customs variables
on: [push]
env:
  DB_HOST: "mypostgres.com"
  DB_USERNAME: "postgres"
jobs:
  job-01:
    env:
      IMAGE_NAME: "wheather-app"
      IAMGE_TAG: "2.0"
    runs-on: ubuntu-latest
    steps:
      - name: Print image name
        run: echo $IMAGE_NAME
      - name: Print db hostname
        run: echo $DB_HOST   
  job-02:
     runs-on: ubuntu-latest
    steps:
      - name: print db hostname
        run: echo ${{env.DB_HOST}}
        env:
         DB_HOST: "localhost"
